# Generated by Django 5.1.1 on 2024-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fperms', '0005_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_internal_group',
            field=models.BooleanField(default=True, verbose_name='is an internal group'),
        ),
    ]
